Primera_Web_App/Controllers/RolController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using OfficeOpenXml;
using Primera_Web_App.Models;


namespace Primera_Web_App.Controllers
{
    public class RolController : Controller
    {
        // GET: Rol
        public ActionResult Index()
        {
            List<RolCLS> listaRol = new List<RolCLS>();
            using (var db = new P_W_A_Entities())
            {
                listaRol = (from rol in db.Rol
                            select new RolCLS
                            {
                                IDROL = rol.IDROL,
                                NOMBRE = rol.NOMBRE,
                                DESCRIPCION = rol.DESCRIPCION,
                                HABILITADO = (int)rol.HABILITADO
                            }).ToList();
            }
            return View(listaRol);
        }

        // GET: Rol/Details/5
        public ActionResult Filtrar(RolCLS oRolCLS)
        {
            string nombreRol = oRolCLS.nombreFiltro;
            List<RolCLS> listaRol = new List<RolCLS>();
            using (var db = new P_W_A_Entities())
            {
                if (nombreRol == null)
                {
                    listaRol = (from rol in db.Rol
                                select new RolCLS
                                {
                                    IDROL = rol.IDROL,
                                    NOMBRE = rol.NOMBRE,
                                    DESCRIPCION = rol.DESCRIPCION,
                                    HABILITADO = (int)rol.HABILITADO
                                }).ToList();
                }
                else
                {
                    listaRol = (from rol in db.Rol
                                where rol.NOMBRE.Contains(nombreRol)
                                select new RolCLS
                                {
                                    IDROL = rol.IDROL,
                                    NOMBRE = rol.NOMBRE,
                                    DESCRIPCION = rol.DESCRIPCION
                                }).ToList();
                }
                return PartialView("_TablaRol", listaRol);
            }

        }


        public string Guardar2(RolCLS oRolCLS, int titulo)
        {
            string rpta = "";
            try
            {
                if (!ModelState.IsValid)
                {
                    var query = (from state in ModelState.Values
                                 from error in state.Errors
                                 select error.ErrorMessage).ToList();
                    rpta += "<ul class = 'list-group'";
                    foreach (var item in query)
                    {
                        rpta += "<li class='list-group-item'>" + item + "</li";
                    }
                    rpta += "'</ul'";
                }
                else
                {
                    using (var db = new P_W_A_Entities())
                    {
                       if (titulo == -1)
                       {
                            Rol oRol = new Rol();
                            oRol.IDROL = oRolCLS.IDROL;
                            oRol.NOMBRE = oRolCLS.NOMBRE;
                            oRol.DESCRIPCION = oRolCLS.DESCRIPCION;
                            oRol.HABILITADO = 1;
                            db.Rol.Add(oRol);
                            rpta = db.SaveChanges().ToString();
                            if (rpta == "0") rpta = "";
                       }else {
                            Rol oRol = db.Rol.Where(p => p.IDROL == titulo).First();
                            oRol.NOMBRE = oRolCLS.NOMBRE;
                            oRol.DESCRIPCION = oRolCLS.DESCRIPCION;
                            rpta = db.SaveChanges().ToString();
                       }
                    }
                }
            }
             catch (Exception ex)
            {
              rpta = "";
            }
            return rpta;
        }

        public string Eliminar(RolCLS oRolCLS)
        {
            string rpta = "";
            try
            {
                int id = oRolCLS.IDROL;
                using (var db = new P_W_A_Entities())
                {
                    Rol oRol = db.Rol.Where(p => p.IDROL == id).First();
                    db.Rol.Remove(oRol);
                    rpta = db.SaveChanges().ToString();                     
                }
            }
            catch (Exception)
            {
                rpta = "";
            }
            return rpta;
        }

        public JsonResult rellenarCampos(int titulo)
        {
            RolCLS oRolCLS = new RolCLS();
            using (var db = new P_W_A_Entities())
            {
                Rol oRol = db.Rol.Where(p => p.IDROL == titulo).First();
                oRolCLS.NOMBRE = oRol.NOMBRE;
                oRolCLS.DESCRIPCION = oRol.DESCRIPCION;
                oRolCLS.HABILITADO = 1;
            }
            return Json(oRolCLS, JsonRequestBehavior.AllowGet);
        }

    }
}

Primera_Web_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>@ViewBag.Title -- Mi Aplicación ASP.NET --</title>
            @Styles.Render("~/Content/css")
            @Scripts.Render("~/bundles/modernizr")
        </head>
            <body>
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            @Html.ActionLink("Aplicacion en MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                                <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                                <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                                <li>@Html.ActionLink("Empleado", "index", "Empleado")</li>
                                <li>@Html.ActionLink("Roles", "Index", "Rol")</li>
                                <li>@Html.ActionLink("Restaurar Empleados", "EmpEliminado", "Empleado")</li>
                            </ul>
                            <ul align="right" class="nav navbar-nav navbar-right">
                                <li>@Html.ActionLink("Salir", "Index", "Home")</li>
                            </ul>
                         </div>
                    </div>
                </div>
                <div class="container body-content">
                    <ul align="right" class="nav navbar-nav navbar-right"><strong>Bienvenido </strong> @HttpContext.Current.Session["Saludo"]</ul>
                    @RenderBody()
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - Mi Aplicación ASP.NET</p>
                    </footer>
                </div>

                @Scripts.Render("~/bundles/jquery")
                 <script src="~/Scripts/jquery-3.4.1.js"></script>
                 <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
                @Scripts.Render("~/bundles/bootstrap")
                @RenderSection("scripts", required: false)
            </body>
    </html>