Primera_Web_App/Models/Empleado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primera_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IDEMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATO { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<int> IDTIPOUSUARIO { get; set; }
        public Nullable<int> IDTIPOCONTRATO { get; set; }
        public Nullable<int> IDSEXO { get; set; }
        public Nullable<int> HABILITADO { get; set; }
        public Nullable<int> TIENEUSUARIO { get; set; }
        public string TIPOUSUARIO { get; set; }
        public string NUMDOCUMENTO { get; set; }
    
        public virtual Sexo Sexo { get; set; }
    }
}

Primera_Web_App/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using OfficeOpenXml;
using Primera_Web_App.Models;

namespace Primera_Web_App.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        public FileResult generarPDF()
        {
            Document doc = new Document();
            byte[] buffer;
            using (MemoryStream ms = new MemoryStream())
            {
                PdfWriter.GetInstance(doc, ms);
                doc.Open();

                Paragraph titulo = new Paragraph("Listado Empleados");
                titulo.Alignment = Element.ALIGN_CENTER;
                doc.Add(titulo);

                Paragraph ESPACIO = new Paragraph(" ");
                doc.Add(ESPACIO);
                PdfPTable tabla = new PdfPTable(4);
                float[] values = new float[4] { 30, 40, 40, 40 };
                tabla.SetWidths(values);

                PdfPCell celda1 = new PdfPCell(new Phrase("ID EMPLEADO"));
                celda1.BackgroundColor = new BaseColor(130, 130, 130);
                celda1.HorizontalAlignment = PdfPCell.ALIGN_CENTER;
                tabla.AddCell(celda1);

                PdfPCell celda2 = new PdfPCell(new Phrase("NOMBRE"));
                celda2.BackgroundColor = new BaseColor(130, 130, 130);
                celda2.HorizontalAlignment = PdfPCell.ALIGN_CENTER;
                tabla.AddCell(celda2);

                PdfPCell celda3 = new PdfPCell(new Phrase("APELLIDO"));
                celda3.BackgroundColor = new BaseColor(130, 130, 130);
                celda3.HorizontalAlignment = PdfPCell.ALIGN_CENTER;
                tabla.AddCell(celda3);

                PdfPCell celda4 = new PdfPCell(new Phrase("SUELDO"));
                celda4.BackgroundColor = new BaseColor(130, 130, 130);
                celda4.HorizontalAlignment = PdfPCell.ALIGN_CENTER;
                tabla.AddCell(celda4);

                List<EmpleadoCLS> lista = (List<EmpleadoCLS>)Session["lista"];
                int num_reg = lista.Count();
                for (int i = 0; i < num_reg; i++)
                {
                    tabla.AddCell(lista[i].IDEMPLEADO.ToString());
                    tabla.AddCell(lista[i].NOMBRE);
                    tabla.AddCell(lista[i].APELLIDO);
                    tabla.AddCell(lista[i].SUELDO.ToString());
                }
                doc.Add(tabla);
                doc.Close();
                buffer = ms.ToArray();
                return File(buffer, "application/pdf");
            }
        }

        public FileResult generarExel()
        {
            byte[] buffer;
            using (MemoryStream ms = new MemoryStream())
            {
                ExcelPackage ep = new ExcelPackage();
                ep.Workbook.Worksheets.Add("Reporte Empleado");
                ExcelWorksheet ew = ep.Workbook.Worksheets[1];
                ew.Cells[1, 1].Value = "ID Empleado";
                ew.Cells[1, 2].Value = "Nombre";
                ew.Cells[1, 3].Value = "Apellido";
                ew.Cells[1, 4].Value = "Fecha Contrato";
                ew.Cells[1, 5].Value = "Sueldo";


                ew.Column(1).Width = 20;
                ew.Column(2).Width = 60;
                ew.Column(3).Width = 60;
                ew.Column(4).Width = 60;
                ew.Column(5).Width = 60;


                using (var range = ew.Cells[1, 1, 1, 6])
                {
                    range.Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                    range.Style.Font.Color.SetColor(Color.White);
                    range.Style.Fill.BackgroundColor.SetColor(Color.DarkKhaki);
                }
                List<EmpleadoCLS> lista = (List<EmpleadoCLS>)Session["lista"];
                int nregistros = lista.Count;
                for (int i = 0; i < nregistros; i++)
                {
                    ew.Cells[i + 2, 1].Value = lista[i].IDEMPLEADO;
                    ew.Cells[i + 2, 2].Value = lista[i].NOMBRE;
                    ew.Cells[i + 2, 3].Value = lista[i].APELLIDO;
                    ew.Cells[i + 2, 4].Value = lista[i].FECHACONTRATO;
                    ew.Cells[i + 2, 5].Value = lista[i].SUELDO;
                }
                ep.SaveAs(ms);
                buffer = ms.ToArray();
            }
            return File(buffer, "application/vdn.ms-exel");
        }

        public ActionResult Index(EmpleadoCLS oEmpleadoCLS)
        {
            string apeEmp = oEmpleadoCLS.APELLIDO;
            List<EmpleadoCLS> lst = null;
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                using (var db = new P_W_A_Entities())
                {
                    if (oEmpleadoCLS.APELLIDO == null)
                    {
                        lst = (from empleado in db.Empleado
                               where empleado.HABILITADO == 1
                               select new EmpleadoCLS
                               {
                                   IDEMPLEADO = empleado.IDEMPLEADO,
                                   NOMBRE = empleado.NOMBRE,
                                   APELLIDO = empleado.APELLIDO,
                                   FECHACONTRATO = (DateTime)empleado.FECHACONTRATO,
                                   SUELDO = (decimal)empleado.SUELDO,
                                   IDSEXO = (int)empleado.IDSEXO,
                               }).ToList();
                        Session["lista"] = lst;
                    }
                    else
                    {
                        lst = (from empleado in db.Empleado
                               where empleado.HABILITADO == 1 && empleado.APELLIDO.Contains(apeEmp)
                               select new EmpleadoCLS
                               {
                                   IDEMPLEADO = empleado.IDEMPLEADO,
                                   NOMBRE = empleado.NOMBRE,
                                   APELLIDO = empleado.APELLIDO,
                                   FECHACONTRATO = (DateTime)empleado.FECHACONTRATO,
                                   SUELDO = (decimal)empleado.SUELDO,
                                   IDSEXO = (int)empleado.IDSEXO,
                               }).ToList();
                        Session["lista"] = lst;
                    }

                    return View(lst);
                }
            }
        }

        public ActionResult EmpEliminado(EmpleadoCLS oEmpleadoCLS)
        {
            string apeEmp = oEmpleadoCLS.APELLIDO;
            List<EmpleadoCLS> lst = null;
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                using (var db = new P_W_A_Entities())
                {
                    if (oEmpleadoCLS.APELLIDO == null)
                    {
                        lst = (from empleado in db.Empleado
                               where empleado.HABILITADO == 0
                               select new EmpleadoCLS
                               {
                                   IDEMPLEADO = empleado.IDEMPLEADO,
                                   NOMBRE = empleado.NOMBRE,
                                   APELLIDO = empleado.APELLIDO,
                                   FECHACONTRATO = (DateTime)empleado.FECHACONTRATO,
                                   SUELDO = (decimal)empleado.SUELDO,
                                   IDSEXO = (int)empleado.IDSEXO,
                               }).ToList();
                        Session["lista"] = lst;
                    }
                    else
                    {
                        lst = (from empleado in db.Empleado
                               where empleado.HABILITADO == 0 && empleado.APELLIDO.Contains(apeEmp)
                               select new EmpleadoCLS
                               {
                                   IDEMPLEADO = empleado.IDEMPLEADO,
                                   NOMBRE = empleado.NOMBRE,
                                   APELLIDO = empleado.APELLIDO,
                                   FECHACONTRATO = (DateTime)empleado.FECHACONTRATO,
                                   SUELDO = (decimal)empleado.SUELDO,
                                   IDSEXO = (int)empleado.IDSEXO,
                               }).ToList();
                        Session["lista"] = lst;
                    }

                    return View(lst);
                }
            }
        }

        List<SelectListItem> listaSexo;
        private void LlenarSexo()
        {
            using (var db = new P_W_A_Entities())
            {
                listaSexo = (from d in db.Sexo
                             select new SelectListItem
                             {
                                 Text = d.DESCRIPCION,
                                 Value = d.IDSEXO.ToString(),
                             }).ToList();
                listaSexo.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
            }

        }

        // GET: Empleado/Create
        public ActionResult Agregar()
        {
            LlenarSexo();
            ViewBag.lista = listaSexo;
            return View();
        }


        // POST: Empleado/Agregar
        [HttpPost]
        public ActionResult Agregar(EmpleadoCLS oEmpleadoCLS)
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                int cantReg = 0;
                string numdoc = oEmpleadoCLS.NUMDOCUMENTO;
                using (var db = new P_W_A_Entities())
                {

Primera_Web_App/Views/Empleado/Agregar.cshtml
@using Primera_Web_App.Models
@model EmpleadoCLS

@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> lista = (List<SelectListItem>)ViewBag.lista;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Agregar Empleados</title>
    <!-- Referencias de Bootstrap  on line y para el sitio -->
</head>

<body>
    <div class="row">
        <div class="row-cols-6">
            @using (Html.BeginForm("Agregar", "Empleado", FormMethod.Post, new { @id = "frmConfirmacion" }))
            {
                <div>@Html.ValidationSummary()</div>
                <div>
                    @Html.LabelFor(p => p.NOMBRE)
                    @Html.TextBoxFor(p => p.NOMBRE, new { @class = "form-control" })
                    @Html.ValidationMessage("Nombre", new { @class = "text_danger" })
                </div>

                <div>
                    @Html.LabelFor(p => p.APELLIDO)
                    @Html.TextBoxFor(p => p.APELLIDO, new { @class = "form-control" })
                    @Html.ValidationMessage("Apellido", new { @class = "text_danger" })
                </div>

                <div>
                    @Html.LabelFor(p => p.NUMDOCUMENTO)
                    @Html.TextBoxFor(p => p.NUMDOCUMENTO, new { @class = "form-control" })
                    @Html.ValidationMessage("Documento", new { @class = "text_danger" })
                </div>

                <div>
                    @Html.LabelFor(p => p.FECHACONTRATO)
                    @Html.TextBoxFor(p => p.FECHACONTRATO, new { @class = "form-control" })
                </div>

                <div>
                    @Html.LabelFor(p => p.SUELDO)
                    @Html.TextBoxFor(p => p.SUELDO, new { @class = "form-control" })
                    @Html.ValidationMessage("Sueldo", new { @class = "text_danger" })
                </div>

                <div>
                    @Html.LabelFor(p => p.Sexo)
                    @Html.DropDownList("IDSEXO", lista, "Seleccione item", new { @class = "form-control" })
                    @Html.ValidationMessage("Sexo", new { @class = "text-danger" })

                </div>
                <br />
                <div style="margin:auto">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                        Agregar
                    </button>
                    <!--<input type="submit" class="btn btn-primary" value="Agregar" />-->
                    @Html.ActionLink("Retornar", "index", "Empleado", null, new { @class = "btn btn-danger" })
                </div>
            }

        </div>
    </div>
    </body>
</html>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalLongTitle">Agregar Empleado</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>¿Desea Agregar un nuevo Empleado?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" onclick="Agregar()" class="btn btn-primary">  Agregar</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        function Agregar() {
            var frmConfirmacion = document.getElementById("frmConfirmacion");
            frmConfirmacion.submit();
        }
    </script>

Primera_Web_App/Views/Empleado/Editar.cshtml
@model Primera_Web_App.Models.EmpleadoCLS
@{
    ViewBag.Title = "EDITAR";
    List<SelectListItem> listaSexo = (List<SelectListItem>)ViewBag.lista;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EDITAR Empleados</title>
    <!-- Referencias de Bootstrap  on line y para el sitio -->
</head>

  <body>    
    <div class="row">
        <div class="row-cols-6">
            @using (Html.BeginForm("Editar", "Empleado", FormMethod.Post))
            {
                <hr />
                <br />
                <div class="form-group">
                    @Html.LabelFor(p => p.IDEMPLEADO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(p => p.IDEMPLEADO, new { @class = "form-control", @readOnly = true })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(p => p.NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(p => p.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessage("Nombre", new { @class = "text_danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(p => p.APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(p => p.APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessage("Apellido", new { @class = "text_danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(p => p.FECHACONTRATO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(p => p.FECHACONTRATO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(p => p.FECHACONTRATO, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(p => p.SUELDO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(p => p.SUELDO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessage("Sueldo", new { @class = "text_danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(p => p.IDSEXO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.DropDownList("IDSEXO", listaSexo, null, new { @class = "form-control" })
                        @Html.ValidationMessage("Sexo", new { @class = "text-danger" })
                    </div>
                </div>
                <br /><br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-6">
                        @Html.ActionLink("Volver", "Index", "Empleado", null, new { @class = "btn btn-info" })
                        <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
                    </div>
                </div>
             }

        </div>
    </div>
  </body>
</html>

Primera_Web_App/Views/Empleado/EmpEliminado.cshtml
@model List<Primera_Web_App.Models.EmpleadoCLS>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Agregar Empleados</title>
    <!-- Referencias de Bootstrap  on line y para el sitio -->
</head>

<body>

<h2>Listado de Empleados</h2>
@Html.ActionLink("GENERAR PDF", "generarPDF", "Empleado", null, new { @class = "btn btn-primary", @target = " " })
@Html.ActionLink("GENERAR Excel", "generarEXCEL", "Empleado", null, new { @class = "btn btn-success" })

<hr />
@using (Html.BeginForm("EmpEliminado", "Empleado", FormMethod.Get))
{
    @Html.Label("Buscar por Apellido : ")
    @Html.TextBox(" APELLIDO ")
    <input id="Button" type="submit" class="btn btn-warning" value="Filtrar" />
    <hr />

    <table class="table tab-content table-bordered table-hover">
        <thead style="color:darkblue">
            <tr>
                <td>#</td>
                <td width="15%">Nombre</td>
                <td width="15%">Apellido</td>
                <td width="15%">Fecha de Contrato</td>
                <td width="10%">Sueldo</td>
                <td width="5%">Sexo</td>

            </tr>
        </thead>
        <tbody>
            @foreach (var oElemento in Model)
            {
                <tr class="text-warning">
                    <td>@oElemento.IDEMPLEADO</td>
                    <td>@oElemento.NOMBRE</td>
                    <td>@oElemento.APELLIDO</td>
                    <td>@oElemento.FECHACONTRATO</td>
                    <td>@oElemento.SUELDO</td>
                    <td>
                        @if (oElemento.IDSEXO == 1)
                        {<strong>Femenino</strong>}
                        else
                        { <strong>Masculino</strong>}
                    </td>

                    <td align="center">
                        
                        @Html.ActionLink("  Restaurar", "EmpEliminado", "Empleado", new { id = oElemento.IDEMPLEADO }, new { @class = "glyphicon glyphicon-repeat  btn btn-danger", @onclick = "restaurar()" })
                </tr>
            }
        </tbody>
    </table>
}
    </body>
</html>

<script>
    function restaurar() {
        if (confirm("¿Desea Restaurar el Empleado?") == true) {
            alert("El Empleado a sido restaurado correctamente")
        }
    }
</script>

Primera_Web_App/Views/Empleado/index.cshtml
@model List<Primera_Web_App.Models.EmpleadoCLS>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lista de Empleados</title> 
    @*<!-- Referencias de Bootstrap  on line y para el sitio -->
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>*@

</head>

  <body>
    <h2>Listado de Empleados</h2>
    <div>
        @Html.ActionLink("AGREGAR", "Agregar", "Empleado", null, new { @class = "glyphicon glyphicon-plus btn btn-primary" })
        @Html.ActionLink("GENERAR PDF", "generarPDF", "Empleado", null, new { @class = "btn btn-primary", @target = " " })
        @Html.ActionLink("GENERAR Excel", "generarEXCEL", "Empleado", null, new { @class = "btn btn-success" })
    </div>
    <hr />
    @using (Html.BeginForm("Index", "Empleado", FormMethod.Get))
    {
        @Html.Label("Buscar por Apellido :")
        @Html.TextBox("APELLIDO")
        <input id="Button" type="submit" class="btn btn-warning" value="Filtrar" />
        <hr />

        <table class="table tab-content table-bordered table-hover">
            <thead style="color:darkblue">
                <tr>
                    <td>#</td>
                    <td width="15%">Nombre</td>
                    <td width="15%">Apellido</td>
                    <td width="15%">Fecha de Contrato</td>
                    <td width="10%">Sueldo</td>
                    <td width="5%">Sexo</td>

                </tr>
            </thead>
            <tbody>
                @foreach (var oElemento in Model)
                {
                    <tr class="text-warning">
                        <td>@oElemento.IDEMPLEADO</td>
                        <td>@oElemento.NOMBRE</td>
                        <td>@oElemento.APELLIDO</td>
                        <td>@oElemento.FECHACONTRATO</td>
                        <td>@oElemento.SUELDO</td>
                        <td>
                            @if (oElemento.IDSEXO == 1)
                            {<strong>Femenino</strong>}
                            else
                            { <strong>Masculino</strong>}
                        </td>

                        <td align="right">
                            @Html.ActionLink(" ", "Editar", "Empleado", new { id = oElemento.IDEMPLEADO }, new { @class = "glyphicon glyphicon-edit btn btn-primary" })
                            @*Html.ActionLink(" ", "Eliminar", "Empleado", new { id = oElemento.IDEMPLEADO }, new { @class = "glyphicon glyphicon-trash btn btn-danger", @onclick = "eliminar()" })*@
                            <button type="button" onclick="mostrarPopup(@oElemento.IDEMPLEADO)" class="glyphicon glyphicon-trash btn btn-danger" data-toggle="modal" data-target="#exampleModal"></button>
                    </tr>
                }
            </tbody>
        </table>
    }

    @using (Html.BeginForm("Eliminar", "Empleado", FormMethod.Post, new { @id = "frmEliminar" }))
    {
        @Html.Hidden("IDEMPLEADO");
    }

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalLongTitle">Baja de Empleado</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>¿Desea Eliminar al Empleado?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" onclick="Eliminar()" class="btn btn-primary">Agregar</button>
                </div>
            </div>
        </div>
    </div>
      </body>
</html>

    <script>
        function mostrarPopup(IDEMPLEADO) {
            document.getElementById("IDEMPLEADO").value = IDEMPLEADO;

        }
        function eliminar() {
            var frmEliminar = document.getElementById("frmEliminar");
            frmEliminar.submit();
        }
    </script>